### PR TITLE
add support for DeepL

### PR DESCRIPTION
**Pull request by topce**
fix
https://github.com/codegrue/auto-translate-json/issues/31

did not test (does not have a key) 
but according to docs it should work
https://www.deepl.com/docs-api/translating-text/example/

### CODE REVIEW

**Comment by topce** [comment]
Hello @codegrue 
can you please review and merge this PR

**Comment by codegrue** [comment]
Hey are you interested in being a contributor to this project. I see you have added a lot to it and I appreciate that. This would let you check in directly and publish to the app store.

**Comment by topce** [comment]
Hello @codegrue

Yes I am interested .
Thank you!

**Comment by codegrue** [comment]
I appreciate the help. I am swamped and have been unable to get in to test all the new pull requests.

**Pull request merged**
