### PR TITLE
add  support for aws and azure

### PR DESCRIPTION
**Pull request by topce**
update docs with new feaures
fix linting problmes
update  all libraries
add command to format code
format code with npm run format

### CODE REVIEW

**Comment by topce** [comment]
Hi @codegrue  
It is done 
Please test Google and Azure ,
I test AWS and it was working OK.
Hope did not break something ;-)

**Comment by topce** [comment]
@codegrue  any news on this one ?

**Comment by topce** [comment]
fix https://github.com/codegrue/auto-translate-json/issues/13

**Comment by topce** [comment]
@codegrue  ?

**Comment by codegrue** [comment]
Everything is merged and ready to go. But I am having issues getting it to package. I put in a issue to the vsce project, but if anyone can try to package on your machine and let me know if it works...?

`vsce package`

https://github.com/microsoft/vscode-vsce/issues/680

**Comment by topce** [comment]
hi @codegrue 
for me it is working with node version v16.13.1 without any code changes

**Comment by topce** [comment]
@codegrue 
what error do  you have ?
I tested with latest vsce
vsce --version
2.6.3 and it works

**Pull request merged**
